import math


POWER_MW = 100.0
CAPACITY_MWH = 200.0

MIN_SOC_PCT = 0.10
MAX_SOC_PCT = 0.90
INITIAL_SOC_PCT = 0.50

ROUND_TRIP_EFFICIENCY = 0.90

INTERVAL_MINUTES = 5
INTERVAL_HOURS = INTERVAL_MINUTES / 60

CHARGE_EFFICIENCY = math.sqrt(ROUND_TRIP_EFFICIENCY)
DISCHARGE_EFFICIENCY = math.sqrt(ROUND_TRIP_EFFICIENCY)

MIN_SOC_MWH = CAPACITY_MWH * MIN_SOC_PCT
MAX_SOC_MWH = CAPACITY_MWH * MAX_SOC_PCT
INITIAL_SOC_MWH = CAPACITY_MWH * INITIAL_SOC_PCT
